GRANT EXECUTE ON FUNCTION add_user_deposit(VARCHAR, VARCHAR, TEXT, TEXT, VARCHAR, VARCHAR, VARCHAR, TEXT, VARCHAR, TEXT, NUMERIC) TO PUBLIC;
GRANT EXECUTE ON FUNCTION get_deposits_by_userid(VARCHAR) to public;
GRANT EXECUTE ON FUNCTION get_deposits_by_address(VARCHAR, VARCHAR) to public;