DROP FUNCTION IF EXISTS get_order_by_id(UUID);
DROP FUNCTION IF EXISTS get_orders_by_userid(VARCHAR);
DROP FUNCTION IF EXISTS get_orders_by_address(VARCHAR, VARCHAR);
DROP FUNCTION IF EXITST sign_order(UUID);
DROP FUNCTION IF EXISTS create_order(VARCHAR, VARCHAR, NUMERIC, VARCHAR, NUMERIC, NUMERIC, NUMERIC);
