DROP FUNCTION IF EXISTS get_or_create_user(VARCHAR, VARCHAR);
DROP FUNCTION IF EXISTS get_user_by_userid(VARCHAR);
DROP FUNCTION IF EXISTS public.add_user_deposit(VARCHAR, VARCHAR, TEXT, TEXT, VARCHAR, VARCHAR, VARCHAR, TEXT, VARCHAR, TEXT, NUMERIC);
