GRANT EXECUTE ON FUNCTION get_user_by_userid(VARCHAR) TO public;
GRANT EXECUTE ON FUNCTION get_or_create_user(VARCHAR, VARCHAR) to public;
GRANT EXECUTE ON FUNCTION add_user_deposit(VARCHAR, VARCHAR, TEXT, TEXT, VARCHAR, VARCHAR, VARCHAR, TEXT, VARCHAR, TEXT, NUMERIC) TO PUBLIC;