name: Supabase Cron Job

on:
  schedule:
    - cron: "*/5 * * * *" # Every 48 hours (2 days)

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Log to Supabase
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: |
          curl -X POST "${SUPABASE_URL}/rest/v1/debug_logs" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${SUPABASE_SERVICE_ROLE_KEY}" \
            -H "Prefer: return=minimal" \
            -d '{
              "log_level": "POKE",
              "error": "",
              "message": "",
              "context": ""
            }'
